// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '#',
    appId: '1:200898261368:web:0a72bd8f10432ba5b5d88d',
    messagingSenderId: '200898261368',
    projectId: 'assignment-2-b248b',
    authDomain: 'assignment-2-b248b.firebaseapp.com',
    storageBucket: 'assignment-2-b248b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '#',
    appId: '1:200898261368:android:4c6f08c469fcafbeb5d88d',
    messagingSenderId: '200898261368',
    projectId: 'assignment-2-b248b',
    storageBucket: 'assignment-2-b248b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '#',
    appId: '1:200898261368:ios:ab5960eda320bfb7b5d88d',
    messagingSenderId: '200898261368',
    projectId: 'assignment-2-b248b',
    storageBucket: 'assignment-2-b248b.firebasestorage.app',
    iosBundleId: 'com.example.assignment2w',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '#',
    appId: '1:200898261368:ios:ab5960eda320bfb7b5d88d',
    messagingSenderId: '200898261368',
    projectId: 'assignment-2-b248b',
    storageBucket: 'assignment-2-b248b.firebasestorage.app',
    iosBundleId: 'com.example.assignment2w',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '#',
    appId: '1:200898261368:web:25dafbadf62b337eb5d88d',
    messagingSenderId: '200898261368',
    projectId: 'assignment-2-b248b',
    authDomain: 'assignment-2-b248b.firebaseapp.com',
    storageBucket: 'assignment-2-b248b.firebasestorage.app',
  );
}
